DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

CREATE TABLE department(
	id int AUTO_INCREMENT PRIMARY KEY,
	name varchar(15) UNIQUE NOT NULL
);
    
CREATE TABLE role(
	id int AUTO_INCREMENT PRIMARY KEY,
	title varchar(45) UNIQUE NOT NULL,
  salary decimal(10,2) UNSIGNED NOT NULL,
  department_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE 
);

CREATE TABLE employee (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(15) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE,
  manager_id INT UNSIGNED,
  FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE SET NULL
);